### ISSUE TITLE
Laminas\ServiceManager\Exception\InvalidArgumentException with CustomVocab 2.0.0 + Omeka-s 4.0.1

### ISSUE THREAD

**Issue by cy-altern** [omeka-s-modules/CustomVocab#39]
With an Omeka-s 4.0.1 + PHP 8.1 (migration from version 3 to version 4) I got this error if the CustomVocab module is activated :
```
Laminas\ServiceManager\Exception\InvalidArgumentException: An invalid abstract factory was registered. Expected an instance of or a valid class name resolving to an implementation of "Laminas\ServiceManager\AbstractFactoryInterface", but "string" was received. in .../html/vendor/laminas/laminas-servicemanager/src/Exception/InvalidArgumentException.php:39
```

Additionally the admin page `.../admin/custom-vocab` throw this error :
```
Error: Class "CustomVocab\Controller\IndexController" not found in .../html/vendor/laminas/laminas-servicemanager/src/Factory/InvokableFactory.php:27
```

_Note : this is a test version so it could be possible to gave acces to the instance if somebody need to investigate "in place"_

**Comment by jimsafley** [comment]
What version of CustomVocab are you using? What's the backtrace for the first exception?

**Comment by cy-altern** [comment]
version of CustomVocab : 2.0.0 (branch master up to date : `git pull` made this morning)

First error display :
```
Laminas\ServiceManager\Exception\InvalidArgumentException
An invalid abstract factory was registered. Expected an instance of or a valid class name resolving to an implementation of "Laminas\ServiceManager\AbstractFactoryInterface", but "string" was received.
```
and detailed stack trace :
```
Laminas\ServiceManager\Exception\InvalidArgumentException: An invalid abstract factory was registered. Expected an instance of or a valid class name resolving to an implementation of "Laminas\ServiceManager\AbstractFactoryInterface", but "string" was received. in .../html/vendor/laminas/laminas-servicemanager/src/Exception/InvalidArgumentException.php:39
Stack trace:
#0 .../html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(913): Laminas\ServiceManager\Exception\InvalidArgumentException::fromInvalidAbstractFactory()
#1 .../html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(354): Laminas\ServiceManager\ServiceManager->resolveAbstractFactoryInstance()
#2 .../html/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(127): Laminas\ServiceManager\ServiceManager->configure()
#3 .../html/application/src/ServiceManager/AbstractPluginManager.php(48): Laminas\ServiceManager\AbstractPluginManager->configure()
#4 .../html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(167): Omeka\ServiceManager\AbstractPluginManager->configure()
#5 .../html/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(92): Laminas\ServiceManager\ServiceManager->__construct()
#6 .../html/application/src/ServiceManager/AbstractPluginManager.php(32): Laminas\ServiceManager\AbstractPluginManager->__construct()
#7 .../html/application/src/Service/DataTypeManagerFactory.php(16): Omeka\ServiceManager\AbstractPluginManager->__construct()
#8 .../html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(615): Omeka\Service\DataTypeManagerFactory->__invoke()
#9 .../html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#10 .../html/application/src/Api/Representation/ValueRepresentation.php(31): Laminas\ServiceManager\ServiceManager->get()
#11 .../html/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(280): Omeka\Api\Representation\ValueRepresentation->__construct()
#12 .../html/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(346): Omeka\Api\Representation\AbstractResourceEntityRepresentation->values()
#13 .../html/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(636): Omeka\Api\Representation\AbstractResourceEntityRepresentation->value()
#14 .../html/themes/centerrow/view/common/block-layout/browse-preview.phtml(40): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayDescription()
#15 .../html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#16 .../html/vendor/laminas/laminas-view/src/Helper/Partial.php(63): Laminas\View\Renderer\PhpRenderer->render()
#17 .../html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Laminas\View\Helper\Partial->__invoke()
#18 .../html/application/src/Site/BlockLayout/BrowsePreview.php(170): Laminas\View\Renderer\PhpRenderer->__call()
#19 .../html/application/src/View/Helper/BlockLayout.php(124): Omeka\Site\BlockLayout\BrowsePreview->render()
#20 .../html/application/view/omeka/site/page/content.phtml(9): Omeka\View\Helper\BlockLayout->render()
#21 .../html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('...')
#22 .../html/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render()
#23 .../html/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#24 .../html/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#25 .../html/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render()
#26 .../html/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren()
#27 .../html/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render()
#28 .../html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render()
#29 .../html/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#30 .../html/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent()
#31 .../html/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest()
#32 .../html/index.php(21): Laminas\Mvc\Application->run()
#33 {main}
```

**Comment by jimsafley** [comment]
The error means it can't find the abstract data type factory that's assigned in `config/module.config.php`. According to the backtrace, this happens when looking at a site page containing a browse preview block that contains a resource with a custom vocab description. Does this sound correct? I can't reproduce the bug using the same versions and workflow. I would ask if you're using a non-standard CustomVocab, but that doesn't seem likely since you pulled from master.

**Comment by cy-altern** [comment]
> According to the backtrace, this happens when looking at a site page containing a browse preview block that contains a resource with a custom vocab description. Does this sound correct?

this seems to be correct given the error message but looking in the database the `custom_vocab` table is empty...

The `config/module.config.php` file has not been modified since the installation of the module, its content is the following:
```
namespace CustomVocab;

return [
    'api_adapters' => [
        'invokables' => [
            'custom_vocabs' => Api\Adapter\CustomVocabAdapter::class,
        ],
    ],
    'entity_manager' => [
        'mapping_classes_paths' => [
            dirname(__DIR__) . '/src/Entity',
        ],
        'proxy_paths' => [
            dirname(__DIR__) . '/data/doctrine-proxies',
        ],
    ],
    'service_manager' => [
        'factories' => [
            'CustomVocab\ImportExport' => Service\Stdlib\ImportExportFactory::class,
        ],
    ],
    'data_types' => [
        'abstract_factories' => [
            Service\DataType\CustomVocabFactory::class,
        ],
    ],
    'view_manager' => [
        'template_path_stack' => [
            dirname(__DIR__) . '/view',
        ],
    ],
    'form_elements' => [
        'factories' => [
            Form\Element\CustomVocabSelect::class => Service\Form\Element\CustomVocabSelectFactory::class,
        ],
    ],
    'controllers' => [
        'factories' => [
            'CustomVocab\Controller\Admin\Index' => Service\Controller\Admin\IndexControllerFactory::class,
        ],
    ],
    'datascribe_data_types' => [
        'factories' => [
            'custom_vocab_select' => Service\DatascribeDataType\CustomVocabSelectFactory::class,
        ],
    ],
    'navigation' => [
        'AdminModule' => [
            [
                'label' => 'Custom Vocab', // @translate
                'route' => 'admin/custom-vocab',
                'resource' => 'CustomVocab\Controller\Admin\Index',
                'privilege' => 'browse',
                'pages' => [
                    [
                        'route' => 'admin/custom-vocab/default',
                        'visible' => false,
                    ],
                    [
                        'route' => 'admin/custom-vocab/id',
                        'visible' => false,
                    ],
                ],
            ],
        ],
    ],
    'router' => [
        'routes' => [
            'admin' => [
                'child_routes' => [
                    'custom-vocab' => [
                        'type' => \Laminas\Router\Http\Literal::class,
                        'options' => [
                            'route' => '/custom-vocab',
                            'defaults' => [
                                '__NAMESPACE__' => 'CustomVocab\Controller\Admin',
                                'controller' => 'index',
                                'action' => 'browse',
                            ],
                        ],
                        'may_terminate' => true,
                        'child_routes' => [
                            'default' => [
                                'type' => \Laminas\Router\Http\Segment::class,
                                'options' => [
                                    'route' => '/:action',
                                    'constraints' => [
                                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                    ],
                                    'defaults' => [
                                        'action' => 'add',
                                    ],
                                ],
                            ],
                            'id' => [
                                'type' => \Laminas\Router\Http\Segment::class,
                                'options' => [
                                    'route' => '/:id[/:action]',
                                    'constraints' => [
                                        'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                        'id' => '\d+',
                                    ],
                                    'defaults' => [
                                        'action' => 'show',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'translator' => [
        'translation_file_patterns' => [
            [
                'type' => 'gettext',
                'base_dir' => dirname(__DIR__) . '/language',
                'pattern' => '%s.mo',
                'text_domain' => null,
            ],
        ],
    ],
];
```
